services:
    ml-jupyter:
        image: ml-jupyter
        hostname: ml-jupyter
        container_name: ml-jupyter
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/home/jovyan/work
            - ./data:/home/jovyan/data
        ports:
            - 8888:8888
        command: "start-notebook.sh --NotebookApp.token="
