services:
    ml-jupyter:
        image: ml-jupyter
        hostname: ml-jupyter
        container_name: ml-jupyter
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./code:/home/jovyan/code
        ports:
            - 8888:8888
        command: "start-notebook.sh --NotebookApp.token="
